name: GitHub Profile Summary Cards

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_SUMMARY_CARDS }}
        with:
          USERNAME: Kevin-Perdomo
          BRANCH_NAME: "output"
          UTC_OFFSET: -3
          AUTO_PUSH: true
